sudo: false
language: node_js
node_js:
  - "5.6.0"
script: npm run build:prod
before_script: chmod +x ./.travis.before.sh && ./.travis.before.sh
after_success: chmod +x ./.travis.success.sh && ./.travis.success.sh
env:
  global:
    - CXX=g++-4.8
    - secure: "XiYhWpvlTl5RD5jw54EIUmGtzvMfw64ZW/KYC2pVL05Z6H0GIIBdzwcmVvThhtxWrExiP6WA8iZwsg0T4EGXrzqg8kguSai/ln6gRiv+4eMEm6jTH9uIl4/T5h0XZ8p5A4YqPKOSIxKLdvCctwi5LkR2MLjk2hB0S5aGlI0Q6c7AxUmgh+Qopk8qrsuj2p4J7c9ugMiwcKcNM6pyQ/bre5IZU1I6vy4jJlgd27AmJ44fM5yCQwfGiSs9zEDIDhwTLZsOr4P0YTapubGmn8BQTJnr3J8eHRwK/lQP4nBWuWWKPQYgDQxmHJEijNKLuRLZVbadUxovvPHqWXY1wWO7swOwiPevCVPlPMoC2rlbj9SpPN4m+mYTfUNsF/5RHCiuDKzmQrWmBukROdEGgWMfzFobUcHGdneEqGWz2ffTeIFPXmwdHuWQ2kfVLnGvu2Cm6Ilks4uxiyZhHaD5slpywTEbEg3fp16dLwk/PBdx3Zrk9YQwKr7rxllQAE5FGLs9oekQ/6YMoEVtRnpMUZNN8Er2TclV8kMhYuGD9COUPgjQ8dWNRnSSqXay97jOWOYvMN/xg9pSPDzzmQ/4zkptKQxvIqxk4WQGN67U1w31V0NGgvFFyBjrKALXDXtf/h++ZhlnkTZWKwiJ0o9LVkVl21SQKeWrjqDP0S+zjSDze8Q="
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8