sudo: false
language: node_js
node_js:
  - "5.6.0"
script: npm run build:prod
before_script: chmod +x ./.travis.before.sh && ./.travis.before.sh
after_success: chmod +x ./.travis.success.sh && ./.travis.success.sh
env:
  global:
    - CXX=g++-4.8
    - secure: ksZ+I9jnT3gu4cjMjj8mPwyNHAAaR2W/rY/OsB3x3aiZ2xSGFVhbTQRTOPI0VkdGjtCzLWSrA4uy0gcKBiiTNsr+G5eBvMcQJyBhtldUdGGneYf0h5jUOJrwOV1w3GWd0PaKHMlBo7+BPLMLTbY6Nxactd6QimFx5zhKQgwzAbH5nsQeeGk2FzykoaycUVaUMFQ7YYXl//WcZDOgn1B7s+Qmk6CFxjS6Et2bC9WMJB/7GbcEwYyLSkldmCJibESrPFjGuiFMwx38XZS8SK0lgNs/yXOI7iLh6DsYkjMA6YHTld8c6os7iEd/7FBexskASMRzpTpgT91p9AwEAVWbZhpoEVJEmXX1tYujVMYIY+HzAWcRf6qXikASMaE7nAK1VrdzGyDwxVkfbkCssUoPkHQii4iQb1DD+B7jJ/RrfgGlVCNmtI/NGnHoAnSHQldcedWBgDDOMtnQ0XjPiooEPkP+gZ7FsdhEvd9fv7FzSCpytX3kOaQknH1SXr1Gq+RagTzwd0FVXBeMm644InaxCkgtVf/PO7JUvXs/MvEBNCvdcJGnlAf5rk1Gd36vBjrNWDiDrxUWOsGz9Pl8eemzE8rcTjLO3cYCv3yIYrJb8dNgY7+QTDBDZ9qRjnDeS2eCjSWF/Fur8aqa39ERAB0MI6BWFMxsHSBso5UP/OFZr1g=
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
